### ISSUE TITLE
Textures Flicker like crazy with Plains Update

### ISSUE THREAD

**Issue by svmnotn** [GloriousEggroll/warframe-linux#4] opened 2017-10-13 02:46 UTC
Just reinstalled for the update, using lutris, running with the default options for the launcher, default Low preset except High texture memory.

Still persists with 22.0.1

**Comment by slin31** [comment] 2017-10-13 10:08
Can confirm. I'm having the same problem with the new update.
Some textures flicker, others simply disappear at certain camera angles (they become see through) and some are just black.
I tried disabling graphics settings to see if the problem is with any one of them, but I could not determine what is causing this.
Disabling dx10/11 did not help either.

**Comment by svmnotn** [comment] 2017-10-14 14:59
yes that fixed the flicker and missing textures! :D

**Comment by GloriousEggroll** [comment] 2017-10-14 15:03
Cool deal, sorry I haven't been able to check this, been at Disney the last few days with family, if you can submit a pull request I can get it merged.

**Comment by GloriousEggroll** [comment] 2017-10-14 15:04
If not I may be able to handle it tonight or tomorriw

**Comment by GloriousEggroll** [comment] 2017-10-14 15:05
Can you try just removing mesa_glthreads and leaving the threaded optimizations line?

**Comment by slin31** [comment] 2017-10-15 02:52
I made a pull request, and I left threaded optimizations enabled as requested.
I did some testing and threaded optimizations doesn't seem to cause any issues, guess I should have tested them one by one and not all at once.
I'm not sure if there is a performance difference between mesa threads and CSMT but at least it runs properly now.

**Closed** 2017-10-15 03:06 UTC
