### ISSUE TITLE
dxvk support?

### ISSUE THREAD

**Issue by NeroBurner** [GloriousEggroll/warframe-linux#33] opened 2018-03-24 07:16 UTC
With all the latest fuss about dxvk (dx11 to vulkan renderer) and it showing very promising results: does it work with warframe?

**Comment by NeroBurner** [comment] 2018-03-24 09:32
tried it, does not work
OS: Arch Linux
GPU: GeForce GTX 780 Ti
Driver: 390.42.0
Vulkan: 1.0.65

winetricks version used to install vulkansdk: `20180217-next - sha256sum: 5a31e01536c6d3383b2b576333f7b9eae5c21bfd69ac925c8d0b36691420870d`

I think a required feature is not yet implemented by dxvk
```
5.477 Sys [Info]: Resource load completed in one pass and 1.3s (inherited 9 of 1550), Frame peak: 217ms
5.495 Gfx [Info]: Creating dynamic texture: /Textures/DynamicTexture0
err:   D3D11DeferredContext::Map: Not implemented
5.497 Gfx [Warning]: D3DAssert: DeviceContext().Map(texData.mTexture, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped) returned 0x80004001

5.497 Error [Info]: Assertion Failure
Error [Debug]: Loaded unexpected version of dbghelp.dll from C:\windows\system32\dbghelp.dll
```

Full crash log
[dxvk-crash.txt](https://github.com/GloriousEggroll/warframe-linux/files/1844204/dxvk-crash.txt)

**Comment by NeroBurner** [comment] 2018-03-24 10:01
reported at DXVK: https://github.com/doitsujin/dxvk/issues/198

**Comment by NeroBurner** [comment] 2018-03-24 12:35
tested mit current master of dxvk (`dxvk-git 20180324.87d6fde-1`)

```
5.377 Gfx [Info]: Creating dynamic texture: /Textures/DynamicTexture0
err:   D3D11DeferredContext::MapImage: Not implemented
5.380 Gfx [Warning]: D3DAssert: DeviceContext().Map(texData.mTexture, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped) returned 0x80004001
```

**Comment by GloriousEggroll** [comment] 2018-03-24 16:40
I've already reported this to the developer, the game required deferred contexts which he partially implemented, but it also requires the map/unmap functions of it which are not implemented yet.
I'm closing this bug report because it is a dxvk bug, not related to this script

**Closed by GloriousEggroll** 2018-03-24 16:40 UTC

**Comment by RealGrep** [comment] 2018-04-26 22:15
Thought you'd appreciate a note on this topic from me, since I've got it running pretty much flawlessly with dxvk. I've been playing maybe 12 hours and a large number of missions (but not Onslaught) and the frame rate is excellent, and it has not crashed once on me.

I'm on Arch Linux, with a NVidia FTX 1050 Ti. So, this is what I did. I started with Lutris, and your script, and used that as my starting point. I copied it, and installed dxvk (AUR's dxvk-bin 0.42-1). I cloned your dxvk-tools repo and ran installvulkan.sh on the prefix with VULKANSDK=1 DXVK=1. I also saw xact didn't seem to be installed, and I swear it was supposed to. Not sure, but I did winetricks it in.

I have script that sort of bypass your update procedure, but basically, the launcher refused to launch the 64 bit version for me (DirectX 10 and 11 greyed). So I'm launching the 64 bit binary directly from another script based on yours.

I did install d3d11_43 before I installed vulkan into the Wine prefix. I don't think that did anything useful, but just in case, I mention it.

Versions are:
dxvk 0.42
vulkan 1.0.65
wine-staging 3.6 (from Arch's repos, not Lutris.)
nvidia 390.48
System otherwise quite up to date.

Side note: I love your script, but it seems to want to download about 15GB or so of stuff for the most trivial of patches. Updater is working for me, except the thing where it can't overwrite the running launcher binary (killing the launcher and copying the binary is one of the scripts.) Bit manual, but hey, this method is working.

If there's any other info you'd like me to dig up, let me know. Hopefully that's comprehensive enough to be reproducible. Though I assume you'd not do the hacky script thing I did. Mine is just yours without all the updating stuff, more or less.

Thanks a lot for all the useful work you've done on this stuff! And might I say, this is glorious. Almost always pegged at 60 fps (the cap), and stable. :)
